version: "3.2"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    container_name: es01
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      -  /etc/localtime:/etc/localtime
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: "es01"
      discovery.seed_hosts: "es02,es03"
      cluster.initial_master_nodes: "es01,es02,es03"
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    container_name: es02
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      -  /etc/localtime:/etc/localtime
    environment:
      node.name: "es02"
      discovery.seed_hosts: "es01,es03"
      cluster.initial_master_nodes: "es01,es02,es03"
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    container_name: es03
    volumes:
      - esdata03:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      -  /etc/localtime:/etc/localtime
    environment:
      node.name: "es03"
      discovery.seed_hosts: "es01,es02"
      cluster.initial_master_nodes: "es01,es02,es03"
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:$ELK_VERSION
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      -  /etc/localtime:/etc/localtime
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk
    depends_on:
      - es01
      - es02
      - es03

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      -  /etc/localtime:/etc/localtime
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - es01
      - es02
      - es03
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
      - xpack.security.enabled=true

  curator:
    image: curator:comm
    user: root
    container_name: curator
    volumes:
      - ./extensions/curator/config:/usr/share/curator/config 
      - ./extensions/curator/logs:/opt/elasticsearch-curator/logs
      - ./extensions/curator/cron/crontab:/etc/crontab
      - /etc/localtime:/etc/localtime
    networks:
      - elk
    depends_on:
      - es01
      - es02
      - es03

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
networks:
  elk:
    driver: bridge
