# Curator configuration
# https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html

client:
  hosts:
    - es01
  port: 9200
  http_auth: elastic:123456

logging:
  loglevel: INFO
  logfile: /opt/elasticsearch-curator/logs/run.log
  logformat: default
